### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by Shatur** [lanza/vim-cmake#1]
After installing plugin I have the following error at startup:
![изображение](https://user-images.githubusercontent.com/22453358/78498590-ebc88780-7753-11ea-8477-517682362259.png)
I using Neovim 0.4.3. The error occurs even with the default configuration and without any plugins (expect this, of course).

**Comment by lanza** [comment]
Neat, didn't know anybody else was using this. [Fixed](https://github.com/lanza/vim-cmake/commit/f9300074898772eafe7715dc1c126853aadbf73c).

**Comment by Shatur** [comment]
Thanks!

Just trying to find best way to work with CMake in Vim. Previously I used [asynctasks](https://github.com/skywind3000/asynctasks.vim), it very universal, but I can't conveniently select target to run. Your plugin looks like good alternative.
